### Fetch all tasks
GET http://localhost:5002/api/v1/tasks
Content-Type: application/json

### Create new task
POST http://localhost:5002/api/v1/tasks
Content-Type: application/json

{
  "title": "Super Important Task 2",
  "date": "2022-01-01T12:00:00Z",
  "description": "The project manager is angry, @dev_team please fix as soon as possible",
  "priority": "High",
  "status": "Todo"
}

### Update status of an existed task
PATCH http://localhost:5002/api/v1/tasks
Content-Type: application/json

{
  "id": "115e9864-b527-43ce-adcf-47a7bd511949",
  "status": "InProgress"
}
### 115e9864-b527-43ce-adcf-47a7bd511949